package Forms;

import Entities.AccountHistoryEntity;
import Entities.User;
import Services.AccountService;
import com.sun.jdi.Value;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 * @author mprzybyla
 */
public class ATM extends javax.swing.JFrame {

    /**
     * Creates new form ATM
     */
    public ATM() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoggedUserPanel = new javax.swing.JPanel();
        LoggedUserLabel = new javax.swing.JLabel();
        LoggedUserInfo = new javax.swing.JLabel();
        MainMenu = new javax.swing.JMenuBar();
        Customers = new javax.swing.JMenu();
        LoginItem = new javax.swing.JMenuItem();
        RegisterItem = new javax.swing.JMenuItem();
        WithdrawItem = new javax.swing.JMenuItem();
        DepositCashItem = new javax.swing.JMenuItem();
        TransferMenuItem = new javax.swing.JMenuItem();
        HistoryItem = new javax.swing.JMenuItem();
        AccountBalanceItem = new javax.swing.JMenuItem();
        LogoutItem = new javax.swing.JMenuItem();
        ATMConfig = new javax.swing.JMenu();
        ATMManager = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bankomat Przybyła Maciej");
        setBackground(new java.awt.Color(51, 51, 51));
        setForeground(java.awt.Color.red);
        setLocationByPlatform(true);

        LoggedUserPanel.setBackground(new java.awt.Color(153, 153, 153));

        LoggedUserLabel.setText("Zalogowany użytkownik:");

        javax.swing.GroupLayout LoggedUserPanelLayout = new javax.swing.GroupLayout(LoggedUserPanel);
        LoggedUserPanel.setLayout(LoggedUserPanelLayout);
        LoggedUserPanelLayout.setHorizontalGroup(
            LoggedUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoggedUserPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LoggedUserLabel)
                .addGap(34, 34, 34)
                .addComponent(LoggedUserInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(503, Short.MAX_VALUE))
        );
        LoggedUserPanelLayout.setVerticalGroup(
            LoggedUserPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoggedUserLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(LoggedUserInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        LoggedUserLabel.setEnabled(false);
        LoggedUserInfo.setEnabled(false);

        MainMenu.setBackground(new java.awt.Color(255, 0, 102));
        MainMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, java.awt.Color.black, null, null));
        MainMenu.setForeground(new java.awt.Color(102, 255, 51));
        MainMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Customers.setText("Panel klienta");
        Customers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CustomersMouseClicked(evt);
            }
        });

        LoginItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        LoginItem.setText("Zaloguj");
        LoginItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LoginItemMouseClicked(evt);
            }
        });
        LoginItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginItemActionPerformed(evt);
            }
        });
        Customers.add(LoginItem);

        RegisterItem.setText("Rejestracja klienta");
        RegisterItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterItemActionPerformed(evt);
            }
        });
        Customers.add(RegisterItem);

        WithdrawItem.setText("Wypłata środków");
        WithdrawItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawItemActionPerformed(evt);
            }
        });
        Customers.add(WithdrawItem);
        WithdrawItem.setVisible(false);

        DepositCashItem.setText("Wpłata środków");
        DepositCashItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DepositCashItemActionPerformed(evt);
            }
        });
        Customers.add(DepositCashItem);
        DepositCashItem.setVisible(false);

        TransferMenuItem.setText("Wykonaj przelew");
        TransferMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferMenuItemActionPerformed(evt);
            }
        });
        Customers.add(TransferMenuItem);
        TransferMenuItem.setVisible(false);

        HistoryItem.setText("Pobierz wyciąg");
        HistoryItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HistoryItemActionPerformed(evt);
            }
        });
        Customers.add(HistoryItem);
        HistoryItem.setVisible(false);

        AccountBalanceItem.setText("Stan konta");
        AccountBalanceItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountBalanceItemActionPerformed(evt);
            }
        });
        Customers.add(AccountBalanceItem);
        AccountBalanceItem.setVisible(false);

        LogoutItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        LogoutItem.setText("Wyloguj");
        LogoutItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutItemActionPerformed(evt);
            }
        });
        Customers.add(LogoutItem);
        LogoutItem.setVisible(false);

        MainMenu.add(Customers);

        ATMConfig.setText("Administracja");

        ATMManager.setText("Zarządzaj bankomatem");
        ATMManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ATMManagerActionPerformed(evt);
            }
        });
        ATMConfig.add(ATMManager);

        MainMenu.add(ATMConfig);
        ATMConfig.setVisible(false);

        setJMenuBar(MainMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LoggedUserPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(500, Short.MAX_VALUE)
                .addComponent(LoggedUserPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterItemActionPerformed
        // TODO add your handling code here:
        Register registerDialog = new Register(this,true);
        registerDialog.setLocationRelativeTo(this);
        registerDialog.show();
    }//GEN-LAST:event_RegisterItemActionPerformed

    private void ATMManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ATMManagerActionPerformed
        // TODO add your handling code here:
        AtmService serviceDialog = new AtmService(this,true);
        serviceDialog.setLocationRelativeTo(this);
        serviceDialog.show();
    }//GEN-LAST:event_ATMManagerActionPerformed

    private void CustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CustomersMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomersMouseClicked

    private void LogoutItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogoutItemActionPerformed
        // TODO add your handling code here:
            LoginItem.setVisible(true);
            RegisterItem.setVisible(true);
            LogoutItem.setVisible(false);
            AccountBalanceItem.enable(false);
            AccountBalanceItem.setVisible(false);
            LoggedUserLabel.setEnabled(false);
            LoggedUserInfo.setEnabled(false);
            LoggedUserInfo.setText("");
            ATMConfig.setVisible(false);
            WithdrawItem.setVisible(false);
            DepositCashItem.setVisible(false);
            HistoryItem.setVisible(false);
            TransferMenuItem.setVisible(false);
            this.loggedUser=null;
    }//GEN-LAST:event_LogoutItemActionPerformed

    private void AccountBalanceItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountBalanceItemActionPerformed
        // TODO add your handling code here:
        AccountBalance dialog = new AccountBalance(this,true,this.loggedUser.Id);
        dialog.setLocationRelativeTo(this);
        dialog.show();
    }//GEN-LAST:event_AccountBalanceItemActionPerformed

    private void WithdrawItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawItemActionPerformed
        // TODO add your handling code here:
       Withdraw withdrawDialog = new Withdraw(this, true, this.loggedUser.Id);
       withdrawDialog.setLocationRelativeTo(this);
       withdrawDialog.show();
    }//GEN-LAST:event_WithdrawItemActionPerformed

    private void HistoryItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HistoryItemActionPerformed
        // TODO add your handling code here:
        AccountHistory accountHistoryDialog = new AccountHistory(this,true, this.loggedUser.Id);
        accountHistoryDialog.setLocationRelativeTo(this);
        accountHistoryDialog.show();
        
        
    }//GEN-LAST:event_HistoryItemActionPerformed

    private void DepositCashItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DepositCashItemActionPerformed
        // TODO add your handling code here:
        Deposit depositDialog = new Deposit(this,true,this.loggedUser.Id);
        depositDialog.setLocationRelativeTo(this);
        depositDialog.show();
    }//GEN-LAST:event_DepositCashItemActionPerformed

    private void TransferMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferMenuItemActionPerformed
        // TODO add your handling code here:
        TransferCash transferDialog = new TransferCash(this, true, this.loggedUser);
        transferDialog.setLocationRelativeTo(this);
        transferDialog.show();
    }//GEN-LAST:event_TransferMenuItemActionPerformed

    private void LoginItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginItemActionPerformed
        // TODO add your handling code here:
        Login dialog = new Login(this,true);
        dialog.setLocationRelativeTo(this);
        dialog.show();
        this.loggedUser=dialog.getLoggedUser();

        if(this.loggedUser!=null)
        {
            LoginItem.setVisible(false);
            RegisterItem.setVisible(false);
            LogoutItem.setVisible(true);
            AccountBalanceItem.enable(true);
            AccountBalanceItem.setVisible(true);
            LoggedUserLabel.setEnabled(true);
            LoggedUserInfo.setEnabled(true);
            LoggedUserInfo.setText(loggedUser.FirstName+" "+loggedUser.LastName);
            WithdrawItem.setVisible(true);
            DepositCashItem.setVisible(true);
            HistoryItem.setVisible(true);
            TransferMenuItem.setVisible(true);

            if(loggedUser.FirstName.equals("atm") && loggedUser.LastName.equals("atm"))
            {
                this.atmService=true;
                ATMConfig.setVisible(true);
                WithdrawItem.setVisible(false);
                DepositCashItem.setVisible(false);
                HistoryItem.setVisible(false);
                AccountBalanceItem.setVisible(false);
                TransferMenuItem.setVisible(false);
                LoggedUserInfo.setText("Obsługa bankomatu");

            }
        }

    }//GEN-LAST:event_LoginItemActionPerformed

    private void LoginItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LoginItemMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_LoginItemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ATM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ATM().setVisible(true);
                
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ATMConfig;
    private javax.swing.JMenuItem ATMManager;
    private javax.swing.JMenuItem AccountBalanceItem;
    private javax.swing.JMenu Customers;
    private javax.swing.JMenuItem DepositCashItem;
    private javax.swing.JMenuItem HistoryItem;
    private javax.swing.JLabel LoggedUserInfo;
    private javax.swing.JLabel LoggedUserLabel;
    private javax.swing.JPanel LoggedUserPanel;
    private javax.swing.JMenuItem LoginItem;
    private javax.swing.JMenuItem LogoutItem;
    private javax.swing.JMenuBar MainMenu;
    private javax.swing.JMenuItem RegisterItem;
    private javax.swing.JMenuItem TransferMenuItem;
    private javax.swing.JMenuItem WithdrawItem;
    // End of variables declaration//GEN-END:variables

    private boolean atmService = false;

    /**
     * Get the value of atmService
     *
     * @return the value of atmService
     */
    public boolean isAtmService() {
        return atmService;
    }

    /**
     * Set the value of atmService
     *
     * @param atmService new value of atmService
     */
    public void setAtmService(boolean atmService) {
        this.atmService = atmService;
    }

    private User loggedUser = null;

    /**
     * Get the value of loggedUser
     *
     * @return the value of loggedUser
     */
    public User getLoggedUser() {
        return loggedUser;
    }
}
