package Forms;

import Entities.ATMEntity;
import Services.ATMManageService;
import javax.swing.JOptionPane;

/**
 * @author mprzybyla
 */
public class AtmService extends javax.swing.JDialog {

    /**
     * Creates new form AtmServiceDialog
     */
    public AtmService(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ATMManageService service = new ATMManageService();
        this.atmEntity=service.GetAtmInfo();
        this.CashInAtmView.setText(Integer.toString(this.atmEntity.TotalAvailableCash));
        this.Banknot10Spinner.setValue(this.atmEntity.PLN10);
        this.Banknot20Spinner.setValue(this.atmEntity.PLN20);
        this.Banknot50Spinner.setValue(this.atmEntity.PLN50);
        this.Banknot100Spinner.setValue(this.atmEntity.PLN100);
        this.Banknot200Spinner.setValue(this.atmEntity.PLN200);
        this.Banknot500Spinner.setValue(this.atmEntity.PLN500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Banknot20Label = new javax.swing.JLabel();
        Banknot10Label = new javax.swing.JLabel();
        Banknot100Label = new javax.swing.JLabel();
        Banknot50Label = new javax.swing.JLabel();
        Banknot200Label = new javax.swing.JLabel();
        Banknot500Label = new javax.swing.JLabel();
        OkButton = new javax.swing.JButton();
        Banknot10Spinner = new javax.swing.JSpinner();
        Banknot20Spinner = new javax.swing.JSpinner();
        Banknot50Spinner = new javax.swing.JSpinner();
        Banknot100Spinner = new javax.swing.JSpinner();
        Banknot200Spinner = new javax.swing.JSpinner();
        Banknot500Spinner = new javax.swing.JSpinner();
        CashInATMLabel = new javax.swing.JLabel();
        CashInAtmView = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Banknot20Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot20Label.setText("20 PLN");

        Banknot10Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot10Label.setText("10 PLN");

        Banknot100Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot100Label.setText("100 PLN");

        Banknot50Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot50Label.setText("50 PLN");

        Banknot200Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot200Label.setText("200 PLN");

        Banknot500Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot500Label.setText("500 PLN");

        OkButton.setText("Zatwierdź");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        CashInATMLabel.setText("Ilość pięniędzy w bankomacie:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(CashInATMLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Banknot10Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Banknot10Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Banknot20Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Banknot20Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Banknot50Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Banknot50Spinner))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Banknot100Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Banknot100Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CashInAtmView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Banknot200Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Banknot200Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Banknot500Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                            .addComponent(Banknot500Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Banknot100Label, Banknot10Label, Banknot200Label, Banknot20Label, Banknot500Label, Banknot50Label});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Banknot10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot20Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot50Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot100Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot200Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot500Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Banknot50Spinner)
                        .addComponent(Banknot100Spinner)
                        .addComponent(Banknot200Spinner)
                        .addComponent(Banknot500Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Banknot20Spinner)
                        .addComponent(Banknot10Spinner)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CashInATMLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                            .addComponent(CashInAtmView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(80, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Banknot100Label, Banknot10Label, Banknot200Label, Banknot20Label, Banknot500Label, Banknot50Label});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        // TODO add your handling code here:
        ATMEntity atmTemp = new ATMEntity(this.atmEntity);
        this.atmEntity.PLN10=(Integer)this.Banknot10Spinner.getValue();
        this.atmEntity.PLN20=(Integer)this.Banknot20Spinner.getValue();
        this.atmEntity.PLN50=(Integer)this.Banknot50Spinner.getValue();
        this.atmEntity.PLN100=(Integer)this.Banknot100Spinner.getValue();
        this.atmEntity.PLN200=(Integer)this.Banknot200Spinner.getValue();
        this.atmEntity.PLN500=(Integer)this.Banknot500Spinner.getValue();
        this.atmEntity.refresh();
        if((this.atmEntity.PLN10<0) || (this.atmEntity.PLN20<0) || (this.atmEntity.PLN50<0) || (this.atmEntity.PLN100<0) || (this.atmEntity.PLN200<0) || (this.atmEntity.PLN500<0))
        {
            this.atmEntity=new ATMEntity(atmTemp);
            JOptionPane.showMessageDialog(this, "Brak wybranych banknotów w bankomacie!");
            this.dispose();
        }
        else
        {
        ATMManageService.UpdateAtm(atmEntity);
        this.CashInAtmView.setText(Integer.toString(this.atmEntity.TotalAvailableCash)+" PLN");
        this.dispose();
        }
    }//GEN-LAST:event_OkButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AtmService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AtmService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AtmService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AtmService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AtmService dialog = new AtmService(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                
                dialog.setVisible(true);
                
                
                
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banknot100Label;
    private javax.swing.JSpinner Banknot100Spinner;
    private javax.swing.JLabel Banknot10Label;
    private javax.swing.JSpinner Banknot10Spinner;
    private javax.swing.JLabel Banknot200Label;
    private javax.swing.JSpinner Banknot200Spinner;
    private javax.swing.JLabel Banknot20Label;
    private javax.swing.JSpinner Banknot20Spinner;
    private javax.swing.JLabel Banknot500Label;
    private javax.swing.JSpinner Banknot500Spinner;
    private javax.swing.JLabel Banknot50Label;
    private javax.swing.JSpinner Banknot50Spinner;
    private javax.swing.JLabel CashInATMLabel;
    private javax.swing.JLabel CashInAtmView;
    private javax.swing.JButton OkButton;
    // End of variables declaration//GEN-END:variables

    private ATMEntity atmEntity = null;
    
    /**
     * Get the value of atmEntity
     *
     * @return the value of atmEntity
     */
    public ATMEntity getAtmEntity() {
         return atmEntity;
    }

    /**
     * Set the value of atmEntity
     *
     * @param atmEntity new value of atmEntity
     */
    public void setAtmEntity(ATMEntity atmEntity) {
        this.atmEntity = atmEntity;
    }
}
