package Forms;

import Entities.ATMEntity;
import Services.ATMManageService;
import Services.AccountService;
import javax.swing.JOptionPane;

/**
 * @author mprzybyla
 */
public class Deposit extends javax.swing.JDialog {

    /**
     * Creates new form DepositDialog
     */
    public Deposit(java.awt.Frame parent, boolean modal, int loggedUserId) {
        super(parent, modal);
        initComponents();
        this.loggedUserId=loggedUserId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Banknot20Label = new javax.swing.JLabel();
        Banknot200Spinner = new javax.swing.JSpinner();
        Banknot10Label = new javax.swing.JLabel();
        Banknot500Spinner = new javax.swing.JSpinner();
        Banknot100Label = new javax.swing.JLabel();
        Banknot50Label = new javax.swing.JLabel();
        Banknot200Label = new javax.swing.JLabel();
        Banknot500Label = new javax.swing.JLabel();
        OkButton = new javax.swing.JButton();
        Banknot10Spinner = new javax.swing.JSpinner();
        Banknot20Spinner = new javax.swing.JSpinner();
        Banknot50Spinner = new javax.swing.JSpinner();
        Banknot100Spinner = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Banknot20Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot20Label.setText("20 PLN");

        Banknot10Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot10Label.setText("10 PLN");

        Banknot100Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot100Label.setText("100 PLN");

        Banknot50Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot50Label.setText("50 PLN");

        Banknot200Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot200Label.setText("200 PLN");

        Banknot500Label.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Banknot500Label.setText("500 PLN");

        OkButton.setText("Zatwierdź");
        OkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Banknot10Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(Banknot10Spinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Banknot20Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(Banknot20Spinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Banknot50Label, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(Banknot50Spinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Banknot100Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Banknot100Spinner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Banknot200Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Banknot200Spinner))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Banknot500Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Banknot500Spinner)))
                    .addComponent(OkButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Banknot10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot20Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot50Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot100Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot200Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Banknot500Label, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Banknot500Spinner, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(Banknot200Spinner)
                    .addComponent(Banknot100Spinner)
                    .addComponent(Banknot50Spinner)
                    .addComponent(Banknot10Spinner)
                    .addComponent(Banknot20Spinner))
                .addGap(34, 34, 34)
                .addComponent(OkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkButtonActionPerformed
        // TODO add your handling code here:
        ATMEntity atm = ATMManageService.GetAtmInfo();
        int totalDepositAmount=AccountService.DepositCash(atm, this.loggedUserId, (int)Banknot10Spinner.getValue(), (int)Banknot20Spinner.getValue(), (int)Banknot50Spinner.getValue(), (int)Banknot100Spinner.getValue(), (int)Banknot200Spinner.getValue(), (int)Banknot500Spinner.getValue());
        JOptionPane.showMessageDialog(this, "Wpłacono "+totalDepositAmount+" PLN");
        OkButton.setEnabled(false);
        this.dispose();
    }//GEN-LAST:event_OkButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Banknot100Label;
    private javax.swing.JSpinner Banknot100Spinner;
    private javax.swing.JLabel Banknot10Label;
    private javax.swing.JSpinner Banknot10Spinner;
    private javax.swing.JLabel Banknot200Label;
    private javax.swing.JSpinner Banknot200Spinner;
    private javax.swing.JLabel Banknot20Label;
    private javax.swing.JSpinner Banknot20Spinner;
    private javax.swing.JLabel Banknot500Label;
    private javax.swing.JSpinner Banknot500Spinner;
    private javax.swing.JLabel Banknot50Label;
    private javax.swing.JSpinner Banknot50Spinner;
    private javax.swing.JButton OkButton;
    // End of variables declaration//GEN-END:variables

    private int loggedUserId;

    /**
     * Get the value of loggedUserId
     *
     * @return the value of loggedUserId
     */
    public int getLoggedUserId() {
        return loggedUserId;
    }

    /**
     * Set the value of loggedUserId
     *
     * @param loggedUserId new value of loggedUserId
     */
    public void setLoggedUserId(int loggedUserId) {
        this.loggedUserId = loggedUserId;
    }
}
