package Forms;

import Entities.ATMEntity;
import Services.ATMManageService;
import Services.AccountService;
import javax.swing.JOptionPane;

/**
 * @author mprzybyla
 */
public class Withdraw extends javax.swing.JDialog {

    /**
     * Creates new form WithdrawDialog
     */
    public Withdraw(java.awt.Frame parent, boolean modal, int _userId) {
        super(parent, modal);
        initComponents();
        this.userId=_userId;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        WithdrawSpinner = new javax.swing.JSpinner();
        WithdrawButton = new javax.swing.JButton();
        PLN10Label = new javax.swing.JLabel();
        PLN20Label = new javax.swing.JLabel();
        PLN50Label = new javax.swing.JLabel();
        PLN100Label = new javax.swing.JLabel();
        PLN200Label = new javax.swing.JLabel();
        PLN500Label = new javax.swing.JLabel();
        TotalWithdrawCashLabel = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        TotalText = new javax.swing.JTextPane();
        PLN10Text = new javax.swing.JFormattedTextField();
        PLN20Text = new javax.swing.JFormattedTextField();
        PLN50Text = new javax.swing.JFormattedTextField();
        PLN100Text = new javax.swing.JFormattedTextField();
        PLN200Text = new javax.swing.JFormattedTextField();
        PLN500Text = new javax.swing.JFormattedTextField();
        Kwota = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        WithdrawSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 20000, 10));
        WithdrawSpinner.setFocusable(false);

        WithdrawButton.setText("Wypłać");
        WithdrawButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WithdrawButtonActionPerformed(evt);
            }
        });

        PLN10Label.setText("10 PLN");

        PLN20Label.setText("20 PLN");

        PLN50Label.setText("50 PLN");

        PLN100Label.setText("100 PLN");

        PLN200Label.setText("200 PLN");

        PLN500Label.setText("500 PLN");

        TotalWithdrawCashLabel.setText("Wypłacono:");

        jScrollPane7.setViewportView(TotalText);

        Kwota.setText("Wpisz kwotę");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalWithdrawCashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(WithdrawSpinner, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                                    .addComponent(WithdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(Kwota, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(63, 63, 63)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PLN200Label, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PLN100Label, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PLN500Label, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PLN100Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PLN200Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(PLN500Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(PLN20Label)
                                        .addComponent(PLN50Label))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(PLN20Text, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                                        .addComponent(PLN50Text)))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(PLN10Label)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(PLN10Text))))
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(150, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {PLN100Text, PLN10Text, PLN200Text, PLN20Text, PLN500Text, PLN50Text});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(Kwota, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(WithdrawSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(WithdrawButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PLN10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PLN10Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PLN20Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PLN20Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PLN50Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PLN50Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PLN100Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PLN100Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(PLN200Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PLN200Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PLN500Label, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PLN500Text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalWithdrawCashLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void WithdrawButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WithdrawButtonActionPerformed
        // TODO add your handling code here:
        atmEntity=ATMManageService.GetAtmInfo();
        atmEntity.refresh();
        int amountWithdrawCash = (int)WithdrawSpinner.getValue();
        
        if (amountWithdrawCash%10 != 0) 
        {
            amountWithdrawCash-=amountWithdrawCash%10;   
        }
        
        if(amountWithdrawCash < 10 )
        {
            JOptionPane.showMessageDialog(this, "Minimalna kwota wypłaty to 10 PLN.");
            this.dispose();
        }
        else
        {
            if(atmEntity.TotalAvailableCash<amountWithdrawCash)
            {
                JOptionPane.showMessageDialog(this, "Brak środków w bankomacie!");
                this.dispose();
            }
            else
            {

                int userAccountBalance = AccountService.GetAccountBalance(userId);

                if(userAccountBalance<amountWithdrawCash)
                {
                    JOptionPane.showMessageDialog(this, "Niewystarczająca ilość środków na koncie bankowym!");
                    this.dispose();
                }

                else
                {

                    atmEntity = AccountService.WithdrawCash(atmEntity, userId, amountWithdrawCash, userAccountBalance);

                }
                if(atmEntity.PLN10==0 && atmEntity.PLN20==0 && atmEntity.PLN50==0 && atmEntity.PLN100==0 && atmEntity.PLN200==0 && atmEntity.PLN500==0)
                {
                   JOptionPane.showMessageDialog(this, "Nie można wypłacić wybranej kwoty z powodu niewystarczającej ilości banknotów w bankomacie!"); 
                   this.dispose();
                }
                else
                {
                    PLN10Text.setText(Integer.toString(atmEntity.PLN10));
                    PLN20Text.setText(Integer.toString(atmEntity.PLN20));
                    PLN50Text.setText(Integer.toString(atmEntity.PLN50));
                    PLN100Text.setText(Integer.toString(atmEntity.PLN100));
                    PLN200Text.setText(Integer.toString(atmEntity.PLN200));
                    PLN500Text.setText(Integer.toString(atmEntity.PLN500));
                    TotalText.setText(Integer.toString(atmEntity.TotalAvailableCash)+" PLN");
                }

                this.WithdrawButton.setEnabled(false);
            }
        }
        
        
    }//GEN-LAST:event_WithdrawButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Withdraw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Withdraw dialog = new Withdraw(new javax.swing.JFrame(), true,0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Kwota;
    private javax.swing.JLabel PLN100Label;
    private javax.swing.JFormattedTextField PLN100Text;
    private javax.swing.JLabel PLN10Label;
    private javax.swing.JFormattedTextField PLN10Text;
    private javax.swing.JLabel PLN200Label;
    private javax.swing.JFormattedTextField PLN200Text;
    private javax.swing.JLabel PLN20Label;
    private javax.swing.JFormattedTextField PLN20Text;
    private javax.swing.JLabel PLN500Label;
    private javax.swing.JFormattedTextField PLN500Text;
    private javax.swing.JLabel PLN50Label;
    private javax.swing.JFormattedTextField PLN50Text;
    private javax.swing.JTextPane TotalText;
    private javax.swing.JLabel TotalWithdrawCashLabel;
    private javax.swing.JButton WithdrawButton;
    private javax.swing.JSpinner WithdrawSpinner;
    private javax.swing.JScrollPane jScrollPane7;
    // End of variables declaration//GEN-END:variables

    private int userId;
    private ATMEntity atmEntity=null;


    public int getUserId() {
        return userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }
}
